name: 'TestRigor Trigger'
description: 'A composite action to run testrigor bash scripts with configurable parameters'

inputs:
  testrigor-token:
    description: 'TestRigor authentication token'
    required: true
    sensitive: true
  test-suite-key:
    description: 'TestRigor test suite key'
    required: true
    sensitive: true

runs:
  using: "composite"
  steps:
    - name: Run TestRigor Tests
      shell: bash
      env:
        TESTRIGOR_TOKEN: ${{ inputs.testrigor-token }}
        TEST_SUITE_KEY: ${{ inputs.test-suite-key }}
      run: |
        bash ${{ github.action_path }}/run-tests.sh 